### ISSUE TITLE
How do I submit PR for adding a Jekyll theme?

### ISSUE THREAD

**Issue by zcraber** [sharu725/sveltethemes#4]
Hi, I was trying to submit a Jekyll theme on [jekyll-themes.com](https://jekyll-themes.com/submit). While submitting the form, it gave a message: `Please Login Before Connecting Your Form. If you're the owner of this form, please log in and then try connecting your form again. If you're not the owner of this form, please contact the owner :)`

Clicking the PR button is directed to here. But, I noticed that this repo is for submitting Svelte themes. 
Where do I submit a Jekyll theme?

**Comment by sharu725** [comment]
Thank you @zcraber it was messed up. I have fixed those. The form will work but there is no PR option now. I will leave an email address to contact.
